{
 "title": "weather",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "barometer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "outside",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "barometer_mbar",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "loop" }
     ]
    },
    {
     "alias": "outside",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "barometer_mbar",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "porch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "outTemp_F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "fence",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "soilTemp1_F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "living",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "extraTemp3_F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "basement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "extraTemp1_F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "crawlspace",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "extraTemp5_F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "bath",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "extraTemp2_F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "attic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "extraTemp4_F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "hip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "soilTemp2_F",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    }
   ]
  },
  {
   "title": "humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "porch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "outHumidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "loop" }
     ]
    },
    {
     "alias": "fence",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "soilMoist1_centibar",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "living",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "extrahumid3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "loop" }
     ]
    },
    {
     "alias": "basement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "extraHumid1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "crawlspace",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "extraHumid5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "bath",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "extraHumid2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "attic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "extraHumid4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "hip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "soilMoist2_centibar",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    }
   ]
  },
  {
   "title": "wind speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "alias": "speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "windSpeed_mph",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "loop" }
     ]
    },
    {
     "alias": "gust",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "windGust_mph",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    }
   ]
  },
  {
   "title": "wind direction",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "wind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "windDir",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "gust",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "windGustDir",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    }
   ]
  },
  {
   "title": "solar radiation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "actual",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "radiation_Wpm2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "theoretical maximum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "maxSolarRad",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    }
   ]
  },
  {
   "title": "rain (in)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dayRain_in",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "* 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "month",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monthRain_in",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "* 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "year",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "yearRain_in",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "* 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "rain",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "targets": [
    {
     "alias": "5-minute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rain_in",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "hour",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hourRain_in",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    },
    {
     "alias": "24-hour",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rain24_in",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    }
   ]
  },
  {
   "title": "evapotranspiration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ET_cm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    }
   ]
  },
  {
   "title": "lightning",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "strikes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lightning_strike_count_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    }
   ]
  },
  {
   "title": "lightning",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "targets": [
    {
     "alias": "distance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lightning_distance_mile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "binding", "operator": "=", "value": "archive" }
     ]
    }
   ]
  }
 ]
}